import {tintedCamera} from './camera-colors.js';
const make=(w,h)=>Object.assign(document.createElement('canvas'),{width:w,height:h});
const clamp=v=>Math.max(0,Math.min(255,v));
function random(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}}
export function artEffect(source,fx){const w=source.width,h=source.height,u=Math.max(w,h)/1000,c=make(w,h),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0);const pixels=ctx.getImageData(0,0,w,h),data=pixels.data,rand=random(7913);
if(fx.type==='liquid'){ctx.fillStyle=fx.color;ctx.fillRect(0,0,w,h);const mask=make(w,h),m=mask.getContext('2d');m.fillStyle='#fff';const count=Math.max(3,Math.round(fx.size/4)),coverage=Math.max(.35,Math.min(1.5,fx.density/100));for(let i=0;i<count;i++){const x=(rand()*1.3-.15)*w,y=(i/(count-1)*1.15-.075)*h,rx=(.2+rand()*.28)*w*coverage,ry=(.1+rand()*.2)*h*coverage;m.save();m.translate(x,y);m.rotate((rand()-.5)*Math.PI);m.beginPath();m.moveTo(-rx,0);m.bezierCurveTo(-rx*.9,-ry*1.5,rx*.6,-ry,rx,0);m.bezierCurveTo(rx*1.3,ry*.7,-rx*.4,ry,-rx,0);m.fill();m.restore()}const inside=make(w,h),ic=inside.getContext('2d');ic.drawImage(source,0,0);ic.globalCompositeOperation='destination-in';ic.drawImage(mask,0,0);ctx.drawImage(inside,0,0);return blend(source,c,fx.strength/100)}
const highlights=make(w,h),hx=highlights.getContext('2d'),bright=hx.createImageData(w,h);const shift=Math.round((fx.aberration??3)*u),noise=(fx.noise??25)/100;
for(let y=0;y<h;y++){for(let x=0;x<w;x++){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2],l=(r*.2126+g*.7152+b*.0722)/255;let rr,gg,bb;if(fx.type==='glow'){const offset=(y*w+Math.min(w-1,x+shift))*4,offset2=(y*w+Math.max(0,x-shift))*4;const red=pixels.data[offset],blue=pixels.data[offset2+2];rr=(red/255-.5)*1.2+.5;gg=(g/255-.5)*1.15+.49;bb=(blue/255-.5)*1.18+.5;const saturation=1.4;rr=l+(rr-l)*saturation;gg=l+(gg-l)*saturation;bb=l+(bb-l)*saturation;rr+=.09*Math.sin(l*Math.PI);bb+=.05*(1-l);rr*=255;gg*=255;bb*=255;}else{const v=Math.max(0,Math.min(1,(l-.08)*1.2));const ink=[6,23,31],paper=[222,251,252];rr=ink[0]+(paper[0]-ink[0])*v;gg=ink[1]+(paper[1]-ink[1])*v;bb=ink[2]+(paper[2]-ink[2])*v;const weave=((x+y)%3===0?-14:5)+Math.sin(x/u*2.2)*9;rr+=weave;gg+=weave;bb+=weave;}const grain=(rand()-.5)*noise*85;data[i]=clamp(rr+grain);data[i+1]=clamp(gg+grain);data[i+2]=clamp(bb+grain);const light=Math.max(0,(l-.58)/.42);bright.data[i]=fx.type==='glow'?255:220;bright.data[i+1]=fx.type==='glow'?185:250;bright.data[i+2]=fx.type==='glow'?232:255;bright.data[i+3]=light*light*220;}}
ctx.putImageData(pixels,0,0);hx.putImageData(bright,0,0);ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=(fx.bloom??45)/70;ctx.filter=`blur(${Math.max(2,fx.size)*u}px)`;ctx.drawImage(highlights,0,0);ctx.filter=`blur(${Math.max(1,fx.size*.28)*u}px)`;ctx.globalAlpha*=.45;ctx.drawImage(highlights,0,0);ctx.restore();if(fx.type==='grunge'){const scratches=fx.scratches??40;ctx.save();ctx.lineWidth=.5*u;for(let i=0;i<scratches*6;i++){ctx.globalAlpha=.08+rand()*.22;ctx.strokeStyle=i%3===0?'#07191e':'#e7ffff';const x=rand()*w,y=rand()*h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(rand()-.5)*u*2,y+(rand()*.45+.02)*h);ctx.stroke()}for(let i=0;i<scratches*15;i++){ctx.globalAlpha=rand()*.6;ctx.fillStyle='#deffff';ctx.fillRect(rand()*w,rand()*h,u*(.4+rand()*2),u*(.4+rand()*2))}ctx.restore()}return blend(source,c,fx.strength/100)}
function blend(source,layer,amount){const c=make(source.width,source.height),x=c.getContext('2d');x.drawImage(source,0,0);x.globalAlpha=amount;x.drawImage(layer,0,0);return c}
// Asset metadata is set after the generated camera frame has been inspected.
export const cameraScreen={x:143/1536,y:199/1024,width:922/1536,height:657/1024};
export function cameraMockup(output,settings,asset){if(!settings.enabled||!asset)return;const w=output.width,h=output.height,content=make(w,h),cx=content.getContext('2d');cx.drawImage(output,0,0);const ctx=output.getContext('2d');ctx.clearRect(0,0,w,h);ctx.fillStyle=settings.background;ctx.fillRect(0,0,w,h);const factor=Math.min(w/asset.width,h/asset.height)*(settings.scale/100),aw=asset.width*factor,ah=asset.height*factor;ctx.save();ctx.translate(w/2,h/2);ctx.rotate(settings.rotation*Math.PI/180);const body=tintedCamera(asset,settings.color);ctx.drawImage(body,-aw/2,-ah/2,aw,ah);const sx=-aw/2+cameraScreen.x*aw,sy=-ah/2+cameraScreen.y*ah,sw=cameraScreen.width*aw,sh=cameraScreen.height*ah;ctx.save();ctx.beginPath();ctx.roundRect(sx,sy,sw,sh,Math.min(sw,sh)*.02);ctx.clip();const k=Math.max(sw/w,sh/h);ctx.filter='brightness(85%) contrast(108%)';ctx.drawImage(content,sx+(sw-w*k)/2,sy+(sh-h*k)/2,w*k,h*k);ctx.filter='none';const glow=ctx.createLinearGradient(sx,sy,sx+sw,sy+sh);glow.addColorStop(0,`rgba(225,245,255,${settings.glare/100})`);glow.addColorStop(.45,'rgba(255,255,255,0)');ctx.fillStyle=glow;ctx.fillRect(sx,sy,sw,sh);ctx.restore();ctx.restore()}
