// Original editable caption recipes based on the supplied visual references.
export const captionPresets=[
 ['핑크 유리 젤리','DLLobster','jelly',{color:'#ff8fbb',strokeColor:'#ffd1e4',outerColor:'#fff5ef',thickness:3,outerWidth:2,depth:5,shadowColor:'#ab426d',highlight:92,glow:10,rotation:-7}],
 ['크림 버터 입체','DLSupermagic','sticker',{color:'#f6f6c5',strokeColor:'#342a27',outerColor:'#fdfade',thickness:5,outerWidth:2,depth:4,shadowColor:'#39312c',tracking:1}],
 ['민트 스티커','DLGumi','sticker',{color:'#aee7dd',strokeColor:'#38504e',outerColor:'#f1fffa',thickness:3,outerWidth:2,depth:3}],
 ['두 겹 핑크 자막','DLSinchon','sticker',{color:'#f6b6d5',strokeColor:'#fff7ed',outerColor:'#606156',thickness:3,outerWidth:2,depth:2}],
 ['보라 낙서','DLKirang','sticker',{color:'#c0a8ed',strokeColor:'#33314c',outerColor:'#dedaff',thickness:2,outerWidth:1,depth:0,decoration:'hearts'}],
 ['체리 긴 그림자','DLYeongdeok','retro',{color:'#fff5d9',strokeColor:'#ed6877',outerColor:'#fff5d9',thickness:3,outerWidth:1,depth:13,depthAngle:135,shadowColor:'#953c57',italic:true}],
 ['카페 네온','DLGreatVibes','neon',{color:'#ff93d0',thickness:3,highlight:95,glow:30,depth:0,rotation:-6}],
 ['블루 형광 자막','DLSokcho','neon',{color:'#7ce9ff',thickness:3,highlight:95,glow:26,depth:0}],
 ['진주빛 손글씨','DLCormorantGaramond','neon',{color:'#e9e6ff',thickness:1,highlight:80,glow:12,depth:0,italic:true,decoration:'stars',rotation:-7}],
 ['핑크 캡슐','DLPark','pill',{color:'#826077',strokeColor:'#f7cfe3',outerColor:'#fff8ea',thickness:0,depth:0,paddingX:40,paddingY:11,radius:80,labelBorder:2,tracking:1}],
 ['크림 말풍선','DLJandari','bubble',{color:'#615b54',strokeColor:'#fffddd',outerColor:'#f9cadb',thickness:0,depth:0,paddingX:30,paddingY:11,radius:35,labelBorder:1}],
 ['하늘 검색창','DLChosun','search',{color:'#617b84',strokeColor:'#e5f9ff',outerColor:'#ffffff',thickness:0,depth:0,paddingX:25,paddingY:12,radius:60,labelBorder:2}],
 ['라임 형광 라벨','DLBitbit','label',{color:'#414638',strokeColor:'#deef99',outerColor:'#343b28',thickness:0,depth:0,paddingX:16,paddingY:7,radius:0,tracking:2,rotation:-3}],
 ['파스텔 티켓','DLChosun','ticket',{color:'#796978',strokeColor:'#ffdeeb',outerColor:'#bfa7b5',thickness:0,depth:0,paddingX:36,paddingY:16,radius:3}],
 ['리본 배너','DLSokcho','ribbon',{color:'#606551',strokeColor:'#f2f2c9',outerColor:'#a3af88',thickness:0,depth:0,paddingX:38,paddingY:12,labelBorder:1}],
 ['픽셀 게임 자막','DLSilkscreen','offset',{color:'#d9eac2',strokeColor:'#4b665e',outerColor:'#283d35',thickness:1,outerWidth:1,depth:5,shadowColor:'#1e3b31',tracking:2}],
 ['크롬 Y2K','DLBerkshireSwash','chrome',{color:'#c2e0ec',strokeColor:'#688596',outerColor:'#ffffff',thickness:1,outerWidth:1,depth:3,shadowColor:'#34485e',decoration:'stars'}],
 ['엔젤 스크립트','DLGreatVibes','plain',{color:'#fff5ef',thickness:0,depth:0,decoration:'wings',outerColor:'#fff5ef',rotation:-4}],
 ['펑키 스크랩','DLMathDonuts','sticker',{color:'#dce8a5',strokeColor:'#3a352d',outerColor:'#e8e4d2',thickness:3,outerWidth:1,depth:0,rotation:-5}],
 ['라인 레터링','DLRye','outline',{color:'#ffdaec',outerColor:'#604b5e',thickness:1.5,outerWidth:1,depth:0,tracking:2}],
 ['복숭아 젤리','DLGumi','jelly',{color:'#ffb99e',strokeColor:'#fff5dc',outerColor:'#fff9eb',thickness:2,outerWidth:1,depth:3,shadowColor:'#b76881',highlight:92,glow:8}],
 ['클래식 로그','DLCormorantGaramond','plain',{color:'#fff8d9',italic:true,tracking:4,thickness:0,depth:0,rotation:-5}],
 ['굵은 스크랩 자막','DLApple','sticker',{color:'#ffffff',strokeColor:'#ff8ec1',outerColor:'#fff5d9',thickness:3,outerWidth:2,depth:0,decoration:'stars'}],
 ['작은 하트 자막','DLPark','plain',{color:'#fff2f5',tracking:2,thickness:0,depth:0,decoration:'hearts',outerColor:'#ffa4c7'}],
];
