const asset=(id,name,file,mood,source,note='제작사 이용 조건 적용')=>({id,name,url:'./assets/fonts/'+file,mood,source,note,group:'한글'});
export const fontCatalog=[
 {id:'Pretendard',name:'프리텐다드',mood:'고딕',group:'기본',note:'OFL',source:'https://github.com/orioncactus/pretendard'},
 asset('DLSokcho','속초바다돋움체','Sokcho.woff2','굵은 제목','https://www.sokcho.go.kr/','속초시 · 출처 표시 · 파일 변형 및 판매 금지'),
 asset('DLKedu','케리스 케듀체','Kedu.woff','귀여운 장식','https://copyright.keris.or.kr/wft/fntDwnldView?fntGrpId=GFT202512150000000000002','KERIS · OFL'),
 {id:'DLWild',name:'김씨 와일드각체',mood:'펑크',group:'한글',source:'https://m.blog.naver.com/wooin21s/224048193298',note:'재배포 금지 안내 · 내 폰트 파일 연결'},
 asset('DLChosun','조선굴림체','ChosunGu.ttf','레트로 자막','https://event.chosun.com/100/100font.html','조선일보 · 원본 형태 유지 · 유료 판매 금지'),
 asset('DLYeongdeok','영덕대게체','Yeongdeok.ttf','강한 제목','https://www.yd.go.kr/?page_id=120264','영덕군 · 원본 형태 유지 · 출처 표시'),
 {id:'DLMoneyPixel',name:'머니그라피 Pixel',group:'한글',mood:'픽셀',url:'https://static.toss.im/assets/homepage/moneygraphy-font/font/Moneygraphy-Pixel_1.1.woff2',source:'https://toss.im/moneygraphy-font',note:'토스 공식 서버에서 불러옴 · 수정 및 재배포 금지'},
 {id:'DLMoneyRound',name:'머니그라피 Rounded',group:'한글',mood:'키치',url:'https://static.toss.im/assets/homepage/moneygraphy-font/font/Moneygraphy-Rounded-1.1.woff2',source:'https://toss.im/moneygraphy-font',note:'토스 공식 서버에서 불러옴 · 수정 및 재배포 금지'},
 asset('DLJandari','HS잔다리체','Jandari.woff2','리듬감 있는 제목','https://blog.naver.com/hp0/224051516140','토활공 · 실제 브랜드·로고 사용은 별도 라이선스 확인'),
 asset('DLBitbit','던파 비트비트체 v2','Bitbit.otf','픽셀','https://df.nexon.com/data/font/dnfbitbitv2','네오플 · 원본 유지 · 저작권 안내 포함'),
 asset('DLKirang','기랑해랑체','KirangHaerang.ttf','자유로운 손글씨','https://fonts.google.com/specimen/Kirang+Haerang','Woowahan Brothers · OFL'),
 asset('DLPark','온글잎 박다현체','ParkDahyun.ttf','포근한 손글씨','https://www.ownglyph.com/trial/11ebf7f8-0997-4f03-a393-0959a07286aa','VoyagerX·손글씨 제공자 · 웹 임베딩용 · 파일 수정·재판매 금지'),
 asset('DLSinchon','신촌랩소디체','Sinchon.woff2','통통한 키치','https://sinchonrhapsody.imweb.me/','서대문구청 · 파일 변형 및 유료 판매 금지'),
 asset('DLGumi','낭만있구미체','GumiRomance.ttf','젤리','https://www.gumi.go.kr/portal/contents.do?mid=0502070000','구미시 · 파일 왜곡·변형 및 판매 금지'),
 asset('DLSupermagic','카페24 슈퍼매직체','Supermagic.woff2','장난스러운 장식','https://fonts.cafe24.com/','카페24 · 동봉 라이선스 적용'),
 asset('DLApple','문경감홍사과체','Apple.woff2','말랑한 제목','https://www.gbmg.go.kr/portal/contents.do?mId=0501110000','문경시 · 파일 왜곡·변형 및 판매 금지'),
 ...[['MathDonuts','Math Donuts','MathDonuts.ttf','각진 판타지','math-donuts'],['Swirls','Swirlsandcurls','SwirlsandCurls.ttf','곡선 장식','swirlsandcurls'],['Zawijasy','zawijasy','Zawijasy.otf','덩굴 장식','zawijasy'],['Rascal','Rascal','Rascal.ttf','펑키','rascal'],['Mieszkanie','Mieszkanie9','Mieszkanie9.otf','비정형','mieszkanie9'],['Floozy','Floozy','Floozy.ttf','레트로 장식','floozy'],['Bigurls','Bigurls','Bigurls.ttf','큰 곡선','bigcurls']].map(([id,name,file,mood,slug])=>({...asset('DL'+id,name,file,mood,'https://www.dafont.com/'+slug+'.font',id==='Floozy'?'Typearound · 상업 이용 시 제작자에게 알림 요청':'배포처 100% Free · 원본 파일 유지'),group:'요청 영문'})),
 ...[['Pretty','Pretty On The Inside','pretty-on-the-insid','배포처 사용 범위 미표기'],['Buttons','Buttons & Patches','buttons-patches','개인용 무료'],['Sabrina','Sabrina','sabrina','배포처 사용 범위 미표기'],['Wizards','Wizards Magic','wizards-magic','개인용 무료 · 임베딩 상업판 별도'],['LoveLetters','Love letters','loveletters','개인용 무료'],['Angelica','Angelica','angelica','개인용 무료']].map(([id,name,slug,note])=>({id:'DL'+id,name,mood:'곡선 장식',group:'요청 영문',source:'https://www.dafont.com/'+slug+'.font',note:note+' · 내 폰트 파일 연결'})),
 ...['Berkshire Swash','Great Vibes','Lobster','Rye','Henny Penny','Mystery Quest','Emilys Candy','Pirata One','Silkscreen','Cormorant Garamond'].map(name=>({id:'DL'+name.replaceAll(' ',''),name,group:'추천 영문',mood:({'Great Vibes':'우아한 필기체','Lobster':'젤리 스크립트','Rye':'빈티지 포스터','Pirata One':'고딕 장식','Silkscreen':'픽셀','Cormorant Garamond':'세리프'})[name]||'곡선 장식',url:'./assets/fonts/'+name.replaceAll(' ','')+'.ttf',source:'https://fonts.google.com/specimen/'+name.replaceAll(' ','+'),note:'Google Fonts · OFL'})),
 ...['Georgia','Impact','monospace','cursive','serif','Arial','Verdana','Tahoma','Trebuchet MS','Courier New','Times New Roman','system-ui'].map(id=>({id,name:id,group:'시스템',mood:'기기 기본 글꼴',note:'기기에 설치된 글꼴 사용'}))
];
const loaded=new Set(['Pretendard',...fontCatalog.filter(f=>f.group==='시스템').map(f=>f.id)]),pending=new Map(),privateFonts=new Map();
export const fontAvailable=id=>loaded.has(id);
export const validFont=id=>fontCatalog.some(f=>f.id===id)||/^DLUser[\da-f]+$/.test(id);
export async function loadFont(id){if(loaded.has(id))return;const f=fontCatalog.find(f=>f.id===id);if(!f?.url)throw Error('이 폰트는 내 폰트 파일을 연결해주세요.');if(!pending.has(id))pending.set(id,(async()=>{const face=new FontFace(id,`url("${f.url}")`);await face.load();document.fonts.add(face);loaded.add(id)})().catch(e=>{pending.delete(id);throw e}));await pending.get(id)}
export async function prepareFonts(){await restorePrivate();return Promise.allSettled(fontCatalog.filter(f=>f.url).map(f=>loadFont(f.id)))}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('dotlab-fonts',1);r.onupgradeneeded=()=>r.result.createObjectStore('fonts',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function installPrivate(entry){const face=new FontFace(entry.id,entry.bytes);await face.load();document.fonts.add(face);loaded.add(entry.id);privateFonts.set(entry.id,entry);if(!fontCatalog.some(f=>f.id===entry.id))fontCatalog.push({id:entry.id,name:entry.name,group:'내 폰트',mood:'직접 추가',note:'사용자 파일 · 이용 조건은 원본 확인'});}
async function restorePrivate(){try{const d=await db(),rows=await new Promise((res,rej)=>{const r=d.transaction('fonts').objectStore('fonts').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});d.close();await Promise.allSettled(rows.map(installPrivate))}catch{}}
export async function importFont(file,target){if(!/\.(ttf|otf|woff2?)$/i.test(file.name)||file.size>10*1024*1024)throw Error('10MB 이하 TTF·OTF·WOFF·WOFF2 파일을 선택해주세요.');const name=file.name.replace(/\.[^.]+$/,''),id=target||'DLUser'+crypto.randomUUID().replaceAll('-',''),entry={id,name,bytes:await file.arrayBuffer()};await installPrivate(entry);try{const d=await db();await new Promise((res,rej)=>{const t=d.transaction('fonts','readwrite');t.objectStore('fonts').put(entry);t.oncomplete=res;t.onerror=()=>rej(t.error)});d.close()}catch{}return id;}
export function fontOptions(){return fontCatalog.filter(f=>fontAvailable(f.id)).map(f=>[f.id,f.name+' · '+f.mood]);}
export function serializedFonts(states){const ids=new Set(states.flatMap(s=>s.layers.filter(l=>l.kind==='text').map(l=>l.font)));return [...privateFonts.values()].filter(f=>ids.has(f.id)).map(f=>{let str='';for(const n of new Uint8Array(f.bytes))str+=String.fromCharCode(n);return{id:f.id,name:f.name,data:btoa(str)}})}
export async function restoreProjectFonts(rows){if(!Array.isArray(rows)||rows.length>30)return;for(const r of rows){if(!validFont(r.id)||typeof r.data!=='string'||r.data.length>14000000)continue;try{const bytes=Uint8Array.from(atob(r.data),c=>c.charCodeAt(0)).buffer;await installPrivate({id:r.id,name:String(r.name).slice(0,100),bytes})}catch{}}}
