import {expandAlpha,matteAlpha} from './mask-refine.js';
import {manualPunch,punchPanels} from './manual-punch.js';
import {lineArt} from './line-art.js';
import {punchComposite} from './punch.js';
import {qualityArt} from './quality-effects.js';
import {paperOutline} from './sticker-border.js';
import {styledText} from './typography.js';
import {prism} from './prism.js';
import {finishEffect,decoratedFrame} from './finish-effects.js';
import {cameraMockup} from './art-effects.js';
import {photoEffect,faceBlur} from './photo-effects.js';
export const canvasOf = (w,h) => Object.assign(document.createElement('canvas'),{width:Math.max(1,Math.round(w)),height:Math.max(1,Math.round(h))});
export const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
export function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export const effects=[['none','원본'],['halftone','망점'],['ring','원형 망점'],['beads','비즈'],['ascii','문자 아트'],['scanlines','스캔라인'],['pixel','픽셀'],['duotone','듀오톤'],['grain','필름 그레인'],['liquid','블롭 펀칭'],['glow','Y2K 글로우'],['grunge','빈티지 크롬'],['poster','흑백 포스터'],['fisheye','피시아이'],['lineart','라인드로잉'],['punk','펑키 그런지'],['pastel','파스텔 빈티지'],['dither','도트 변환'],['prism','프리즘 빛번짐']];
export const baseEffect=()=>({type:'none',size:8,strength:80,density:100,color:'#253821',paper:'#f0f3dc',colored:true,invert:false,bloom:45,aberration:3,noise:25,scratches:40,lineOverlay:true,angle:-25,spread:55,dotSize:3,colors:4,palette:'ice',dither:'floyd',coverage:32,flow:0,offsetX:0,offsetY:0,lineWidth:1.3});
export function initialState(){return {version:1,photo:null,collageStyle:'none',name:'작은 우연의 조합',ratio:'original',composition:'overlay',cleanEffectSwitch:true,punch:{enabled:false,mode:'auto',size:75,rotation:0,gradient:false,second:'#f2bedb',columns:3,items:[],layout:'collage',split:50,color:'#dfff59',paper:'#ffffff',gap:14,margin:18,invert:false},split:35,photoVisible:true,zoom:100,panX:0,panY:0,rotation:0,flip:false,brightness:100,contrast:100,saturation:100,warmth:0,blur:0,segmentationQuality:'precise',segmentationAngles:true,mask:null,maskThreshold:50,maskSoft:6,maskExpand:0,maskMatte:true,maskInvert:false,subjectOnly:false,showMask:false,subjectFront:false,target:'all',effectLayers:[],effectSelection:null,customMask:null,showCustomMask:false,effects:{all:baseEffect(),subject:baseEffect(),background:baseEffect(),custom:baseEffect()},pattern:{enabled:false,shape:'mix',layout:'scatter',count:110,size:18,variance:50,opacity:90,region:'background',seed:19,multicolor:true,color:'#d9ff5f',fill:'solid',cutout:false,punchInvert:false,connect:false,custom:'✦ ☆ ♡ @ # ! $ % ʚ♡ɞ 🪽 🦋',offsetX:0,offsetY:0,groupRotation:0},block:{enabled:false,style:'solid',color:'#d9ff5f',second:'#ffffff',opacity:100,x:0,y:55,width:100,height:45,spacing:16,angle:0,mask:'none'},frame:{type:'none',width:24,color:'#f5f4e8',caption:'test'},layers:[],strokes:[],palette:['#e3ee94','#879c68','#ecebe4','#32634a','#b7d6bd'],animation:{type:'float',speed:1,amount:18},word:{enabled:false,text:'test',size:28,color:'#ffffff',highlight:'#e7ff59',opacity:80,seed:41},calendar:{enabled:false,month:'2026-09',color:'#ffffff'},wire:{enabled:false,color:'#d9ff5f',size:35},nodes:[],faces:[],faceBlur:{enabled:false,amount:24,expand:35,mode:'gaussian'},mockup:{enabled:false,color:'#c0c0c0',scale:93,rotation:0,background:'#141414',glare:15},layout:'single',paperTexture:0,blank:false};}
export function dimensions(s,assets,max=1200){const p=assets.get(s.photo);let ratio=s.ratio==='original'?(p?.width||3)/(p?.height||4):Number(s.ratio.split(':')[0])/Number(s.ratio.split(':')[1]);if(s.ratio==='original'&&s.punch?.enabled&&s.punch.mode==='manual')ratio*=s.punch.layout==='horizontal'?.5:s.punch.layout==='collage'?1:2;return ratio>=1?[max,Math.round(max/ratio)]:[Math.round(max*ratio),max]}
export function photoBox(s,w,h){const k=clamp(s.split??35,10,80)/100;switch(s.composition){case'top':return{x:0,y:0,width:w,height:h*(1-k)};case'bottom':return{x:0,y:h*k,width:w,height:h*(1-k)};case'left':return{x:0,y:0,width:w*(1-k),height:h};case'right':return{x:w*k,y:0,width:w*(1-k),height:h};default:return{x:0,y:0,width:w,height:h}}}
export function drawPhoto(ctx,img,s,w,h){if(!img)return;const box=photoBox(s,w,h),iw=img.width,ih=img.height,quarter=Math.abs(s.rotation%180)===90;const scale=Math.max(box.width/(quarter?ih:iw),box.height/(quarter?iw:ih))*s.zoom/100;ctx.save();ctx.beginPath();ctx.rect(box.x,box.y,box.width,box.height);ctx.clip();ctx.translate(box.x+box.width/2+s.panX*w/100,box.y+box.height/2+s.panY*h/100);ctx.rotate(s.rotation*Math.PI/180);ctx.scale(s.flip?-1:1,1);ctx.drawImage(img,-iw*scale/2,-ih*scale/2,iw*scale,ih*scale);ctx.restore()}
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16))}
function adjusted(source,s){const c=canvasOf(source.width,source.height),x=c.getContext('2d');x.filter=`brightness(${s.brightness}%) contrast(${s.contrast}%) saturate(${s.saturation}%) blur(${s.blur*Math.max(c.width,c.height)/1000}px)`;x.drawImage(source,0,0);x.filter='none';if(s.warmth){x.globalCompositeOperation='soft-light';x.globalAlpha=Math.abs(s.warmth)/150;x.fillStyle=s.warmth>0?'#ff972f':'#287afa';x.fillRect(0,0,c.width,c.height)}return c}
export function effectImage(source,fx){if(fx.type==='none'&&!fx.invert)return source;const w=source.width,h=source.height,c=canvasOf(w,h),ctx=c.getContext('2d',{willReadFrequently:true});const factor=Math.max(w,h)/1000,cell=Math.max(2,fx.size*factor);ctx.drawImage(source,0,0);if(fx.invert){ctx.globalCompositeOperation='difference';ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over'}if(fx.type==='none')return c;if(fx.type==='lineart')return lineArt(c,fx);if(fx.type==='prism')return prism(c,fx);if(['pastel','dither'].includes(fx.type))return finishEffect(c,fx);if(['liquid','glow','grunge'].includes(fx.type))return qualityArt(c,fx);if(['poster','fisheye','lineart','punk'].includes(fx.type))return photoEffect(c,fx);
const pixels=ctx.getImageData(0,0,w,h);const data=pixels.data;const out=canvasOf(w,h),x=out.getContext('2d');const ink=rgb(fx.color),paper=rgb(fx.paper);
if(['duotone','grain'].includes(fx.type)){const noise=rng(517);for(let i=0;i<data.length;i+=4){const light=(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255;if(fx.type==='duotone'){for(let k=0;k<3;k++)data[i+k]=ink[k]+(paper[k]-ink[k])*light;}else{const g=(noise()-.5)*fx.size*8;for(let k=0;k<3;k++)data[i+k]=clamp(data[i+k]+g,0,255)}}x.putImageData(pixels,0,0)}else if(fx.type==='scanlines'){x.drawImage(c,0,0);x.fillStyle=fx.color;for(let y=0;y<h;y+=cell){x.globalAlpha=.55;x.fillRect(0,y,w,Math.max(1,cell*.35))}}else{if(fx.type==='pixel'){x.imageSmoothingEnabled=false;const small=canvasOf(Math.ceil(w/cell),Math.ceil(h/cell));small.getContext('2d').drawImage(c,0,0,small.width,small.height);x.drawImage(small,0,0,w,h)}else{x.fillStyle=fx.paper;x.fillRect(0,0,w,h);x.textAlign='center';x.textBaseline='middle';x.font=`bold ${cell*1.12}px monospace`;
const angle=fx.type==='halftone'?(fx.angle??45)*Math.PI/180:0,cos=Math.cos(angle),sin=Math.sin(angle),reach=Math.hypot(w,h)/2;
for(let yy=-reach;yy<=reach;yy+=cell)for(let xx=-reach;xx<=reach;xx+=cell){const px=w/2+xx*cos-yy*sin,y=h/2+xx*sin+yy*cos;if(px<0||y<0||px>=w||y>=h)continue;let red=0,green=0,blue=0;
for(const [dx,dy]of [[0,0],[-.22,-.22],[.22,-.22],[-.22,.22],[.22,.22]]){const ix=(Math.min(h-1,Math.max(0,Math.floor(y+dy*cell)))*w+Math.min(w-1,Math.max(0,Math.floor(px+dx*cell))))*4;red+=data[ix]/5;green+=data[ix+1]/5;blue+=data[ix+2]/5;}
const light=(red*.2126+green*.7152+blue*.0722)/255,darkness=clamp((1-light-.035)*fx.density/100);x.fillStyle=fx.colored?`rgb(${red},${green},${blue})`:fx.color;x.strokeStyle=x.fillStyle;
if(fx.type==='ascii')x.fillText(' .:-=+*#%@'[Math.min(9,Math.floor(darkness*10))],px,y);else{const rad=cell*(fx.type==='beads'?.46:Math.min(.72,Math.sqrt(darkness/Math.PI)*1.06));if(rad<.15)continue;x.beginPath();x.arc(px,y,rad,0,Math.PI*2);if(fx.type==='ring'){x.lineWidth=Math.max(.5*factor,cell*.09);x.stroke()}else{x.fill();if(fx.type==='beads'){x.beginPath();x.fillStyle=fx.paper;x.arc(px, y,cell*.10,0,Math.PI*2);x.fill()}}}}}}

const final=canvasOf(w,h),f=final.getContext('2d');f.drawImage(c,0,0);f.globalAlpha=fx.strength/100;f.drawImage(out,0,0);return final;}
function compositeMask(layer,mask,region){if(!mask||region==='all')return layer;const c=canvasOf(layer.width,layer.height),x=c.getContext('2d');x.drawImage(layer,0,0);x.globalCompositeOperation=region==='background'?'destination-out':'destination-in';x.drawImage(mask,0,0);return c}
function makeMask(s,assets,w,h){const input=assets.get(s.mask);if(!input)return null;const c=canvasOf(w,h),x=c.getContext('2d',{willReadFrequently:true});drawPhoto(x,input,s,w,h);const d=x.getImageData(0,0,w,h);if(s.maskExpand)expandAlpha(d.data,w,h,s.maskExpand*Math.max(w,h)/1000);const lut=Uint8ClampedArray.from({length:256},(_,i)=>matteAlpha(i/255,s.maskThreshold,s.maskSoft,s.maskMatte)*255);for(let i=0;i<d.data.length;i+=4){let a=lut[d.data[i+3]]/255;if(s.maskInvert)a=1-a;d.data[i]=d.data[i+1]=d.data[i+2]=255;d.data[i+3]=a*255;}x.putImageData(d,0,0);return c}
const mixShapes=['✦','✧','*','♡','☆','+','×','♪','~','^','/','%','&','!'];
export function shapePositions(p,w,h,time=0){const rand=rng(p.seed),out=[];for(let i=0;i<p.count;i++){let x=rand()*w,y=rand()*h;const phase=rand()*Math.PI*2;const col=Math.ceil(Math.sqrt(p.count*w/h)),row=Math.ceil(p.count/col);if(p.layout==='grid'){x=((i%col)+.5)/col*w;y=(Math.floor(i/col)+.5)/row*h}else if(p.layout==='wave'){x=((i%col)+.5)/col*w;y=((Math.floor(i/col)+.5)/row+.08*Math.sin(x/w*Math.PI*4))*h}else if(p.layout==='beam'){const angle=i/p.count*Math.PI*8,r=(.1+.55*rand());x=w*.5+Math.cos(angle)*w*r;y=h*.5+Math.sin(angle)*h*r}else if(p.layout==='rain'){x=((i%col)+.5)/col*w;y=(rand()+i/col*.05)%1*h}else if(p.layout==='edge'){const side=i%4;x=side<2?(side===0?rand()*.16:.84+rand()*.16)*w:rand()*w;y=side>=2?(side===2?rand()*.16:.84+rand()*.16)*h:rand()*h}else if(p.layout==='cloud'){x=w*(.5+(rand()+rand()+rand()-1.5)*.32);y=h*(.5+(rand()+rand()+rand()-1.5)*.32)}else if(p.layout==='wand'){x=i/p.count*w;y=h*(.5+.24*Math.sin(i/p.count*6.28))+(rand()-.5)*h*.08}const size=p.size*Math.max(w,h)/1000*(1-p.variance/200+rand()*p.variance/100);const custom=(p.custom||'✦').trim().split(/\s+/).filter(Boolean);const shape=p.shape==='custom'?custom[Math.floor(rand()*custom.length)]:p.shape==='mix'?mixShapes[Math.floor(rand()*mixShapes.length)]:p.shape==='number'?String(Math.floor(rand()*10)):p.shape==='letter'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[Math.floor(rand()*26)]:p.shape;const angle=(p.groupRotation||0)*Math.PI/180,dx=x-w/2,dy=y-h/2;x=w/2+dx*Math.cos(angle)-dy*Math.sin(angle)+(p.offsetX||0)*w/100;y=h/2+dx*Math.sin(angle)+dy*Math.cos(angle)+(p.offsetY||0)*h/100;out.push({x,y,size,shape,phase,index:i,color:p.multicolor?['#ff3975','#9b40ff','#25d6eb','#7de22e','#ffe735'][i%5]:p.color})}return out}
function patternCanvas(s,w,h,time){const p=s.pattern,c=canvasOf(w,h),x=c.getContext('2d');x.textAlign='center';x.textBaseline='middle';x.lineJoin='round';const positions=shapePositions(p,w,h,time);if(p.connect){x.save();x.globalAlpha=p.opacity/250;x.strokeStyle=p.color;x.lineWidth=Math.max(w,h)/1000;for(let i=1;i<positions.length;i++){const a=positions[i];let best=null,dist=Infinity;for(let j=0;j<i;j++){const b=positions[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<dist){best=b;dist=d}}if(best&&dist<Math.max(w,h)*.25){x.beginPath();x.moveTo(a.x,a.y);x.lineTo(best.x,best.y);x.stroke()}}x.restore()}for(const item of positions){let {x:px,y:py,size,shape,color,phase}=item;let alpha=p.opacity/100;const anim=s.animation;if(time){const v=time*anim.speed*Math.PI*2/4;if(anim.type==='float')py+=Math.sin(v+phase)*anim.amount*Math.max(w,h)/1000;if(anim.type==='twinkle')alpha*=.25+.75*(.5+.5*Math.sin(v+phase));if(anim.type==='orbit'){px+=Math.cos(v+phase)*anim.amount;py+=Math.sin(v+phase)*anim.amount}if(anim.type==='pulse')size*=1+Math.sin(v+phase)*anim.amount/100;if(anim.type==='rain')py=(py+v*h*.1)%h}x.globalAlpha=alpha;x.fillStyle=color;x.strokeStyle=color;x.font=`700 ${size}px Pretendard,"Noto Color Emoji","Apple Color Emoji","Segoe UI Emoji",Arial,sans-serif`;if(p.fill==='outline'){x.lineWidth=Math.max(1,size*.06);x.strokeText(shape,px,py)}else{x.fillText(shape,px,py)}}if(!['solid','outline'].includes(p.fill)){x.globalCompositeOperation='destination-out';x.fillStyle='#000';const gap=Math.max(4,Math.max(w,h)/180);for(let yy=0;yy<h;yy+=gap){if(p.fill==='lines'){x.fillRect(0,yy,w,gap*.4)}else for(let xx=0;xx<w;xx+=gap){x.beginPath();x.arc(xx,yy,gap*.25,0,Math.PI*2);x.fill()}}}return c}
function blockCanvas(s,w,h,pattern,unpunched=false){let b={...s.block};const c=canvasOf(w,h),x=c.getContext('2d');if(s.composition&&s.composition!=='overlay'){const k=s.split;Object.assign(b,{enabled:true,angle:0,mask:'none'});if(s.composition==='top')Object.assign(b,{x:0,y:100-k,width:100,height:k});if(s.composition==='bottom')Object.assign(b,{x:0,y:0,width:100,height:k});if(s.composition==='left')Object.assign(b,{x:100-k,y:0,width:k,height:100});if(s.composition==='right')Object.assign(b,{x:0,y:0,width:k,height:100});}if(!b.enabled)return c;x.save();const bx=b.x*w/100,by=b.y*h/100,bw=b.width*w/100,bh=b.height*h/100;x.translate(bx+bw/2,by+bh/2);x.rotate(b.angle*Math.PI/180);x.beginPath();if(b.mask==='circle')x.ellipse(0,0,bw/2,bh/2,0,0,Math.PI*2);else if(b.mask==='heart'){x.moveTo(0,bh*.45);x.bezierCurveTo(-bw,-bh*.1,-bw*.3,-bh*.85,0,-bh*.23);x.bezierCurveTo(bw*.3,-bh*.85,bw,-bh*.1,0,bh*.45)}else if(b.mask==='diamond'){x.moveTo(0,-bh/2);x.lineTo(bw/2,0);x.lineTo(0,bh/2);x.lineTo(-bw/2,0);x.closePath()}else x.rect(-bw/2,-bh/2,bw,bh);x.clip();x.fillStyle=b.color;x.fillRect(-bw/2,-bh/2,bw,bh);x.fillStyle=b.second;const gap=Math.max(3,b.spacing*Math.max(w,h)/1000);if(b.style==='stripes'){for(let yy=-bh/2;yy<bh/2;yy+=gap*2)x.fillRect(-bw/2,yy,bw,gap)}if(b.style==='vertical'){for(let xx=-bw/2;xx<bw/2;xx+=gap*2)x.fillRect(xx,-bh/2,gap,bh)}if(b.style==='dots'){for(let yy=-bh/2;yy<bh/2;yy+=gap)for(let xx=-bw/2;xx<bw/2;xx+=gap){x.beginPath();x.arc(xx,yy,gap*.2,0,Math.PI*2);x.fill()}}if(b.style==='checker'){for(let yy=0;yy<bh/gap;yy++)for(let xx=0;xx<bw/gap;xx++)if((xx+yy)%2===0)x.fillRect(xx*gap-bw/2,yy*gap-bh/2,gap,gap)}x.restore();if(s.pattern.cutout&&!unpunched){x.globalCompositeOperation=s.pattern.punchInvert?'destination-in':'destination-out';x.drawImage(pattern,0,0)}return c}
export function layerBounds(layer,w,h,assets){let width,height;const unit=Math.max(w,h)/1000;if(layer.kind==='image'){const img=assets.get(layer.asset);width=layer.size*unit;height=width*(img?.height||1)/(img?.width||1)}else{const x=canvasOf(1,1).getContext('2d');x.font=`${layer.italic?'italic ':''}${layer.bold?700:400} ${layer.size*unit}px ${layer.font||'Pretendard'}`;x.letterSpacing=`${(layer.tracking||0)*unit}px`;width=Math.max(...layer.text.split('\n').map(t=>x.measureText(t).width),20);height=layer.size*unit*(1+(layer.text.split('\n').length-1)*(layer.lineHeight??118)/100);}return{x:layer.x*w,y:layer.y*h,width,height}}
export function drawLayer(ctx,l,w,h,assets,time=0){if(l.visible===false)return;const b=layerBounds(l,w,h,assets),unit=Math.max(w,h)/1000;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(l.rotation*Math.PI/180);ctx.globalAlpha=l.opacity/100;if(l.shadow&&l.kind==='image'){ctx.shadowColor='#15151030';ctx.shadowBlur=5*unit;ctx.shadowOffsetY=4*unit}if(l.kind==='image'){const img=assets.get(l.asset);if(img){ctx.filter=`brightness(${l.brightness??100}%) saturate(${l.saturation??100}%) blur(${(l.blur??0)*unit}px)`;if(l.mask==='circle'){ctx.beginPath();ctx.ellipse(0,0,b.width/2,b.height/2,0,0,Math.PI*2);ctx.clip()}if(l.paperBorder){const outline=paperOutline(img,l),scale=b.width/outline.width;ctx.filter='none';ctx.drawImage(outline.canvas,-b.width/2-outline.pad*scale,-b.height/2-outline.pad*scale,outline.canvas.width*scale,outline.canvas.height*scale);ctx.shadowColor='transparent';ctx.shadowBlur=ctx.shadowOffsetY=0;ctx.filter=`brightness(${l.brightness??100}%) saturate(${l.saturation??100}%) blur(${(l.blur??0)*unit}px)`;}ctx.drawImage(img,-b.width/2,-b.height/2,b.width,b.height)}}else{ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${l.italic?'italic ':''}${l.bold?700:400} ${l.size*unit}px ${l.font||'Pretendard'}`;ctx.letterSpacing=`${(l.tracking||0)*unit}px`;ctx.fillStyle=l.color;ctx.strokeStyle=l.color;ctx.lineWidth=1.5*unit;l.text.split('\n').forEach((line,i,lines)=>{const yy=(i-(lines.length-1)/2)*l.size*unit*(l.lineHeight??118)/100;styledText(ctx,line,yy,l,unit)})}ctx.restore()}
function drawStroke(ctx,stroke,w,h,time,s){if(!stroke.points.length)return;const u=Math.max(w,h)/1000;ctx.save();ctx.strokeStyle=stroke.color;ctx.fillStyle=stroke.color;ctx.lineWidth=stroke.size*u;ctx.lineCap='round';ctx.lineJoin='round';if(stroke.mode==='line'){ctx.beginPath();stroke.points.forEach(([px,py],i)=>{let yy=py*h;if(time)yy+=Math.sin(i*.25+time*3)*s.animation.amount*u*.2;i?ctx.lineTo(px*w,yy):ctx.moveTo(px*w,yy)});ctx.stroke()}else{ctx.font=`700 ${stroke.size*u}px Pretendard`;ctx.textAlign='center';ctx.textBaseline='middle';const chars=Array.from(stroke.text||'✦');let distance=0,index=0;stroke.points.forEach(([px,py],i)=>{if(i){const prev=stroke.points[i-1];distance+=Math.hypot((px-prev[0])*w,(py-prev[1])*h)}if(i===0||distance>stroke.size*u*.9){distance=0;ctx.fillText(chars[index++%chars.length],px*w,py*h)}})}ctx.restore()}
function wordGrid(ctx,s,w,h){if(!s.word.enabled)return;const a=s.word,unit=Math.max(w,h)/1000,cell=a.size*unit,cols=Math.max(4,Math.floor(w/cell)),rows=Math.floor(h/cell),random=rng(a.seed);ctx.save();ctx.globalAlpha=a.opacity/100;ctx.font=`600 ${cell*.55}px Pretendard,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';const words=a.text.trim().split(/\s+/).slice(0,8),alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ';const cells=Array.from({length:rows},()=>Array.from({length:cols},()=>alphabet[Math.floor(random()*26)]));words.forEach((word,i)=>{const letters=Array.from(word).slice(0,cols-1),row=Math.floor((i+1)/(words.length+1)*rows),start=Math.floor(random()*(cols-letters.length));letters.forEach((ch,j)=>cells[row][start+j]=ch);ctx.strokeStyle=a.highlight;ctx.lineWidth=2.5*unit;ctx.beginPath();ctx.roundRect((start+.1)*cell,(row+.12)*cell,letters.length*cell-.2*cell,cell*.78,cell*.4);ctx.stroke()});ctx.fillStyle=a.color;cells.forEach((row,y)=>row.forEach((char,x)=>ctx.fillText(char,(x+.5)*cell,(y+.5)*cell)));ctx.restore()}
function drawCalendar(ctx,s,w,h){if(!s.calendar.enabled)return;const date=new Date(`${s.calendar.month}-01T12:00:00`),year=date.getFullYear(),month=date.getMonth(),days=new Date(year,month+1,0).getDate(),offset=date.getDay();ctx.save();ctx.fillStyle=s.calendar.color;const cw=w*.065,startX=w*.07,startY=h*.64;ctx.font=`600 ${cw*.5}px Pretendard`;ctx.textAlign='left';ctx.fillText(`${year} / ${String(month+1).padStart(2,'0')}`,startX,startY-cw);ctx.font=`${cw*.34}px Pretendard`;for(let i=0;i<7;i++)ctx.fillText('SMTWTFS'[i],startX+i*cw,startY);for(let day=1;day<=days;day++){const n=day+offset-1;ctx.fillText(String(day),startX+n%7*cw,startY+(1+Math.floor(n/7))*cw*.85)}ctx.restore()}
function frame(ctx,s,w,h,assets){if(decoratedFrame(ctx,s,w,h,assets))return;const f=s.frame,unit=Math.max(w,h)/1000,b=f.width*unit;if(f.type==='none')return;ctx.save();ctx.strokeStyle=f.color;ctx.fillStyle=f.color;ctx.lineWidth=b;if(f.type==='polaroid'||f.type==='postcard'){ctx.fillRect(0,0,w,b);ctx.fillRect(0,0,b,h);ctx.fillRect(w-b,0,b,h);ctx.fillRect(0,h-b*3.3,w,b*3.3);ctx.fillStyle='#242b20';ctx.textAlign='center';ctx.font=`${Math.max(12,b*.4)}px Pretendard`;ctx.fillText(f.caption,w/2,h-b*1.2)}else{ctx.strokeRect(b/2,b/2,w-b,h-b);if(f.type==='stamp'){ctx.globalCompositeOperation='destination-out';const gap=Math.max(10,b*.9);for(let x=0;x<w;x+=gap){ctx.beginPath();ctx.arc(x,0,gap*.26,0,Math.PI*2);ctx.arc(x,h,gap*.26,0,Math.PI*2);ctx.fill()}for(let y=0;y<h;y+=gap){ctx.beginPath();ctx.arc(0,y,gap*.26,0,Math.PI*2);ctx.arc(w,y,gap*.26,0,Math.PI*2);ctx.fill()}}if(f.type==='ticket'){ctx.globalCompositeOperation='destination-out';for(const x of [0,w]){ctx.beginPath();ctx.arc(x,h*.74,b*.8,0,Math.PI*2);ctx.fill()}ctx.globalCompositeOperation='source-over';ctx.setLineDash([6*unit,6*unit]);ctx.lineWidth=unit;ctx.beginPath();ctx.moveTo(b,h*.74);ctx.lineTo(w-b,h*.74);ctx.stroke()}}ctx.restore()}
function customEffect(base,s,assets,w,h){if(!s.customMask)return base;const selection=canvasOf(w,h);drawPhoto(selection.getContext('2d'),assets.get(s.customMask),s,w,h);const layer=compositeMask(effectImage(base,s.effects.custom),selection,'subject'),out=canvasOf(w,h),ctx=out.getContext('2d');ctx.drawImage(base,0,0);ctx.drawImage(layer,0,0);return out;}
export function render(s,assets,output,{time=0,original=false}={}){const w=output.width,h=output.height,ctx=output.getContext('2d');ctx.clearRect(0,0,w,h);const raw=canvasOf(w,h),r=raw.getContext('2d');if(s.photoVisible&&!s.blank)drawPhoto(r,assets.get(s.photo),s,w,h);else{r.fillStyle=s.frame.color;r.fillRect(0,0,w,h)}if(original){ctx.drawImage(raw,0,0);return{mask:null,subject:null}}
const adjustedPhoto=faceBlur(adjusted(raw,s),s,drawPhoto,assets),base=customEffect(effectImage(adjustedPhoto,s.effects.all),s,assets,w,h),mask=makeMask(s,assets,w,h);ctx.drawImage(base,0,0);let subject=null;if(mask){const bg=effectImage(base,s.effects.background);subject=compositeMask(effectImage(base,s.effects.subject),mask,'subject');ctx.clearRect(0,0,w,h);if(!s.subjectOnly)ctx.drawImage(compositeMask(bg,mask,'background'),0,0);ctx.drawImage(subject,0,0)}
for(const layer of s.effectLayers||[]){if(layer.visible===false)continue;let regionMask=mask;if(layer.region==='custom'){if(!layer.mask)continue;regionMask=canvasOf(w,h);drawPhoto(regionMask.getContext('2d'),assets.get(layer.mask),s,w,h);}if(layer.region!=='all'&&!regionMask)continue;const source=canvasOf(w,h);source.getContext('2d').drawImage(output,0,0);const treated=compositeMask(effectImage(source,layer.fx),regionMask,layer.region==='custom'?'subject':layer.region);ctx.save();ctx.globalAlpha=(layer.opacity??100)/100;ctx.globalCompositeOperation=layer.blend||'source-over';ctx.drawImage(treated,0,0);ctx.restore();}if(mask){subject=compositeMask(output,mask,'subject');}if(s.punch?.enabled){let punched;if(s.punch.mode==='manual'){
const photo=punchPanels(s,w,h).photo,source=canvasOf(photo.w,photo.h);render({...s,punch:{...s.punch,enabled:false},mockup:{...s.mockup,enabled:false},composition:'overlay',pattern:{...s.pattern,enabled:false},block:{...s.block,enabled:false},frame:{...s.frame,type:'none'},layers:[],strokes:[],nodes:[],wire:{...s.wire,enabled:false},word:{...s.word,enabled:false},calendar:{...s.calendar,enabled:false},showMask:false,showCustomMask:false,paperTexture:0},assets,source,{time});punched=manualPunch(source,s,w,h);
}else punched=punchComposite(output,s,patternCanvas,time);ctx.clearRect(0,0,w,h);ctx.drawImage(punched,0,0);}else{const pattern=patternCanvas(s,w,h,time);if(s.pattern.cutout&&s.pattern.enabled){const blockMask=blockCanvas(s,w,h,pattern,true);if(s.composition!=='overlay'){const under=canvasOf(w,h),ux=under.getContext('2d');drawPhoto(ux,assets.get(s.photo),{...s,composition:'overlay'},w,h);ux.globalCompositeOperation='destination-in';ux.drawImage(blockMask,0,0);ctx.drawImage(under,0,0)}const outside=canvasOf(w,h),ox=outside.getContext('2d');ox.drawImage(pattern,0,0);ox.globalCompositeOperation='destination-out';ox.drawImage(blockMask,0,0);ctx.drawImage(compositeMask(outside,mask,s.pattern.region),0,0);}ctx.save();ctx.globalAlpha=s.block.opacity/100;ctx.drawImage(blockCanvas(s,w,h,pattern),0,0);ctx.restore();if(s.pattern.enabled&&!s.pattern.cutout)ctx.drawImage(compositeMask(pattern,mask,s.pattern.region),0,0);}wordGrid(ctx,s,w,h);
for(const l of s.layers)if(l.behind)drawLayer(ctx,l,w,h,assets,time);if(s.subjectFront&&subject)ctx.drawImage(subject,0,0);for(const l of s.layers)if(!l.behind)drawLayer(ctx,l,w,h,assets,time);for(const stroke of s.strokes)drawStroke(ctx,stroke,w,h,time,s);drawCalendar(ctx,s,w,h);
if(s.wire.enabled){ctx.save();ctx.strokeStyle=s.wire.color;ctx.lineWidth=Math.max(w,h)/800;const inset=w*.08,edge=s.wire.size*Math.max(w,h)/1000;ctx.strokeRect(inset,inset,w-2*inset,h-2*inset);for(const [x,y] of [[inset,inset],[w-inset,inset],[inset,h-inset],[w-inset,h-inset]]){ctx.fillStyle=s.wire.color;ctx.fillRect(x-edge*.13,y-edge*.13,edge*.26,edge*.26)}ctx.restore()}
if(s.nodes.length){ctx.save();ctx.strokeStyle=s.pattern.color;ctx.fillStyle=s.pattern.color;ctx.lineWidth=2*Math.max(w,h)/1000;ctx.beginPath();s.nodes.forEach(([x,y],i)=>i?ctx.lineTo(x*w,y*h):ctx.moveTo(x*w,y*h));ctx.stroke();s.nodes.forEach(([x,y],i)=>{const pulse=time?1+.25*Math.sin(time*4-i):1;ctx.beginPath();ctx.arc(x*w,y*h,s.pattern.size*Math.max(w,h)/2000*pulse,0,Math.PI*2);ctx.fill()});ctx.restore()}
if(s.paperTexture>0){const rand=rng(57);ctx.save();ctx.globalAlpha=s.paperTexture/500;ctx.fillStyle='#141610';for(let i=0;i<w*h/60;i++)ctx.fillRect(rand()*w,rand()*h,Math.max(1,w/900),Math.max(1,h/900));ctx.restore()}frame(ctx,s,w,h,assets);if(s.showMask&&mask){ctx.save();const tint=canvasOf(w,h),tx=tint.getContext('2d');tx.fillStyle='#d9ff5f';tx.fillRect(0,0,w,h);tx.globalCompositeOperation='destination-in';tx.drawImage(mask,0,0);ctx.globalAlpha=.45;ctx.drawImage(tint,0,0);ctx.restore()}const previewMask=s.effectSelection?s.effectLayers?.find(l=>l.id===s.effectSelection)?.mask:s.customMask;if(s.showCustomMask&&previewMask){const tint=canvasOf(w,h),tx=tint.getContext('2d');drawPhoto(tx,assets.get(previewMask),s,w,h);tx.globalCompositeOperation='source-in';tx.fillStyle='#b391ff';tx.fillRect(0,0,w,h);ctx.save();ctx.globalAlpha=.35;ctx.drawImage(tint,0,0);ctx.restore();}cameraMockup(output,s.mockup,assets.get('camera-frame'));return{mask,subject}}
